### ISSUE TITLE
How do you work with unions

### ISSUE THREAD

**Issue by AlexandrosMelissas** [Khan/genqlient#157]
Hello. First of all, great library. It really solved my problems. I'm facing an issue where i need to query a field which is a Union type. As far as i understand from the generated code, i am supposed to figure out which type it is via GetTypename func. After that, i'm kinda lost. I'm trying to save the field to another variable which has the type of 1 of the 2 types in the Union but it wont let me because the fetched field is of type Union. Also, i'm sorry if this ends up being a noob question. For example, let's say we have: 
```
type type1 struct {
...
}

type type2 struct {
...
}

// This is the type of the field im getting when i fetch
type type1type2Union  struct {
..implements
..getTypeNameFunc()
}

// Now i need to save the field to a variable

if (type1type2Union.GetTypename) == "type1") { 
  var x type1
  // This is the problem because the fetched field is a union and whatever i do it wont let me assign it to another variable
  x = type1type2Union 
}
 ```

**Comment by benjaminjkraft** [comment]
Thanks for the question!  As you may have realized, mapping GraphQL unions to Go types is a bit awkward because Go doesn't have a first-class disjoint union type.  But genqlient has a few ways to handle it, which are described more [here](https://github.com/Khan/genqlient/blob/main/docs/FAQ.md#-graphql-interfaces).  (That all talks about interfaces, but we treat unions as simply being interfaces with no common fields, so only the first solution described there will make sense.)

For a more specific answer to your question, what you're doing is in a sense accurate, it's just that the Go compiler doesn't know that.  The simplest method is usually to use a Go type switch instead of `GetTypename()`, e.g.
```go
switch val := type1type2Union.(type) {
case *type1:
  // use val, which now has type `type1`
case *type2: // etc.
default:
  panic("unexpected type")
}
```
If you prefer you can also use type assertions (`x, ok := type1type2Union.(*type1)`) to accomplish much the same thing.

Hope that helps -- let me know if you have any more questions!
