### ISSUE TITLE
Invalid schema on schema.graphql

### ISSUE THREAD

**Issue by Khushbukela** [Khan/genqlient#175]
invalid schema: Undefined type String.
 
 for every type, I am getting the same error
 
```
 type ABC implements D & E @key(fields: "id"){
    style: Style
    """ ID of the Style """
    id: ID!
    """ Style name """
    stylename: String
}
```

**Comment by benjaminjkraft** [comment]
Ah, I also ran into this recently -- I believe the problem here is that your schema is invalid, but somehow gqlparser is giving the wrong error message.  (For example, if I put the type you have there as the entire schema, I think the real problem is that `Style` is undefined.)  If you can find a full valid schema which gives this error, please do report that repro!

When I get a chance I'll try to figure out what's going on in gqlparser, and report an issue to them (or cc @StevenACoffman if get there first, I suspect this is a regression from the recent changes).

**Comment by benjaminjkraft** [comment]
Oof, this is actually in genqlient and it's a bit tricksy.  It was introduced in #145 where we added support for schemas that include the prelude (which explicitly defines `String`, etc.) rather than expecting us to; we try parsing both with and without the prelude and see what works.  The problem is if neither works, we need to choose which error. There it's much harder to guess which error is more useful -- if we use the explicit-prelude error but you expected implicit prelude, you get `Undefined type String` for everything instead of e.g. `Undefined type D`, but if we use the implicit-prelude error but you expected explicit-prelude, you get `Cannot redeclare type String` instead of `Undefined type D`, likewise.  Right now we choose the explicit-prelude error, which is perhaps bad for more people, but neither is really right.

Possibly the best thing is to stop guessing and figure out if you want a prelude, namely, we'd parse but not validate the schema, see whether it has e.g. an `ID` type, then use that to guess which way to parse.  That will be a bit more work, but should be doable by inlining `gqlparser.LoadSchema` and `validator.LoadSchema` so we can stick this check in the middle.
