### ISSUE TITLE
Generate fails when building a mutation that takes enum as input.

### ISSUE THREAD

**Issue by DAlperin** [Khan/genqlient#194]
**Describe the bug**
Generate fails when building a mutation that takes enum as input.

**To Reproduce**
The following fails to generate: 
```graphql
# Schema snippet
enum IPAddressType {
  v4
  v6
}
```
```graphql
# Query snippet
mutation AllocateIpAddress($app: ID!, $region: String, $type: IPAddressType) {
    allocateIpAddress(input: {
        appId: $app,
        region: $region,
        type: $type
    }) {
        app {
            name
        }
    }
}
```
```shell
genqlient internal error: failed to gofmt code:
	680:5: expected 'IDENT', found 'type' (and 8 more errors)
	680:5: expected 'IDENT', found 'type' (and 8 more errors)
	680:5: expected 'IDENT', found 'type' (and 8 more errors)
	680:5: expected 'IDENT', found 'type' (and 8 more errors)
	680:5: expected 'IDENT', found 'type' (and 8 more errors)
	680:5: expected 'IDENT', found 'type' (and 8 more errors)
	680:5: expected 'IDENT', found 'type' (and 8 more errors)
	680:5: expected 'IDENT', found 'type' (and 8 more errors)
	680:5: expected 'IDENT', found 'type' (and 8 more errors)---source code---
```
The following slight change generates without issue: 
```graphql
mutation AllocateIpAddress($app: ID!, $region: String) {
    allocateIpAddress(input: {
        appId: $app,
        region: $region,
        type: v4
    }) {
        app {
            name
        }
    }
}
```

**Expected behavior**
The generator should successfully complete. 

**genqlient version**
0.4.0

**Comment by benjaminjkraft** [comment]
Thanks for the report. I think the problem here is actually that the variable name `type` is reserved in Go! I'll leave this bug open to remind us to add a better error message (or munge it*) but the best thing to do is just to change the variable name in the mutation.

*in principle munging it would be nicer, especially since the argument name in Go is really just for the documentation, the user doesn't have to write it. But I'm not sure if that could cause worse collisions, possibly ones that won't get caught at type check. So an error may be easier to think about.

**Comment by DAlperin** [comment]
Ah! That makes sense, can't believe I didn't catch that. Thank you for the quick response!
