### ISSUE TITLE
Question - Is it possible to alter the query field part dynamically

### ISSUE THREAD

**Issue by yirez-tc** [Khan/genqlient#227]
Sorry if this is out of place but I couldn't find an example of this within the documents or I may be searching wrong.

Is it possible to alter the fields part dynamically depending on user input? Maybe we could select which fields to send for in the query? 

```
query GetSomeData (
    $id: [String!],
    # @genqlient(pointer: true)
    $createdAt: String,
    $zipCode:[String!],
   ){
    somedata(
        id:$id,
        createdAt:$createdAt,        
        zipCode:$zipCode,
        ) {
        id,
        createdAt,
        description,
        zipCode,
       #add/remove fields from here - no new fields that don't exist in the full query.
    }
}
```

Thanks

**Comment by benjaminjkraft** [comment]
This is not currently possible with genqlient.

To give a bit more of a sense of why -- since we generate the type for the query at compile time, it's a bit hard to know what it would mean to do this. So in your example genqlient would need to generate something like:
```go
func GetSomeData(...) (*GetSomeDataResponse, error) { ... }

type GetSomeDataResponse struct {
  Somedata GetSomeDataSomedata
}

type GetSomeDataSomedata struct {
  ID string
  ... // other fields
}
```

But then if the user could dynamically add a new field, say `name`, where does that go? `GetSomeDataSomedata` doesn't have a `Name` field to put it in. One could imagine we might generate all possible fields, but it gets pretty complicated pretty fast. So I don't really see this as something genqlient is likely to add, although if you want to explore how we might get around some of these problems ideas are welcome.

One thing you can do with some servers is use the `@skip` decorator to conditionally skip certain fields. That's handled by the server I believe; genqlient should just pass it through. More documentation [here](https://graphql.org/learn/queries/#directives).
